server:
    port: 8080
spring:
    application:
        name: customer
    datasource:
        username: 'root'
        password: 'admin'
        url: jdbc:mysql://localhost:3307/customer
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa: 
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        generate-ddl: true
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true  