version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  admin
    ports:
      - '3307:3306'
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql

volumes:
  mysql-data: