server:
    port: 8081
spring:
    application:
        name: fraud
    data:
        mongodb:
            host: mongo_db
            port: 27017
            database: fraud
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true  