version: '3.1'

services:
  mongo_db:
    container_name: mongoDB
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ~/docker/mongo-data:/var/lib/mongo

volumes:
  mongo-data: